apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: web-only-from-client
  namespace: k8s-book-lab
spec:
  podSelector:
    matchLabels:
      app: web
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          role: client
    ports:
    - protocol: TCP
      port: 8080
